### ISSUE TITLE
ImproperlyConfigured exception running tests for reusable app

### ISSUE THREAD

**Issue by divick** [wq/django-swappable-models#15]
After the changes for my reusable app which already had its test cases working before using django-swappable-models, the test cases have started to fail. 

Here is the stacktrace when running the tests for the reusableapp (in this case it is django-blog-zinnia)

```
Traceback (most recent call last):
  File "./bin/test", line 30, in <module>
    sys.exit(nose.main(argv=['nose', '--with-sfd', '--with-progressive', '--nologcapture', '-s']+sys.argv[1:]))
  File "/home/ubuntu/django-blog-zinnia/eggs/nose-1.3.7-py2.7.egg/nose/core.py", line 121, in __init__
    **extra_args)
  File "/usr/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/home/ubuntu/django-blog-zinnia/eggs/nose-1.3.7-py2.7.egg/nose/core.py", line 145, in parseArgs
    self.config.configure(argv, doc=self.usage())
  File "/home/ubuntu/django-blog-zinnia/eggs/nose-1.3.7-py2.7.egg/nose/config.py", line 347, in configure
    self.plugins.begin()
  File "/home/ubuntu/django-blog-zinnia/eggs/nose-1.3.7-py2.7.egg/nose/plugins/manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "/home/ubuntu/django-blog-zinnia/eggs/nose-1.3.7-py2.7.egg/nose/plugins/manager.py", line 167, in simple
    result = meth(*arg, **kw)
  File "/home/ubuntu/django-blog-zinnia/eggs/nose_sfd-0.4-py2.7.egg/sfd/sfd.py", line 41, in begin
    django.setup()  # Django >= 1.7
  File "/home/ubuntu/django-blog-zinnia/eggs/Django-1.10.5-py2.7.egg/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/ubuntu/django-blog-zinnia/eggs/Django-1.10.5-py2.7.egg/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/ubuntu/django-blog-zinnia/eggs/Django-1.10.5-py2.7.egg/django/contrib/admin/apps.py", line 23, in ready
    self.module.autodiscover()
  File "/home/ubuntu/django-blog-zinnia/eggs/Django-1.10.5-py2.7.egg/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/ubuntu/django-blog-zinnia/eggs/Django-1.10.5-py2.7.egg/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ubuntu/django-blog-zinnia/zinnia/admin/__init__.py", line 6, in <module>
    from zinnia.admin.category import CategoryAdmin
  File "/home/ubuntu/django-blog-zinnia/zinnia/admin/category.py", line 7, in <module>
    from zinnia.admin.forms import CategoryAdminForm
  File "/home/ubuntu/django-blog-zinnia/zinnia/admin/forms.py", line 16, in <module>
    Entry = swapper.load_model("zinnia", "Entry")
  File "/home/ubuntu/Env/zinnia/lib/python2.7/site-packages/swapper/__init__.py", line 94, in load_model
    "Could not find {name}!".format(name=join(app_label, model))
django.core.exceptions.ImproperlyConfigured: Could not find zinnia.Entry!
make: *** [test] Error 1
```

The code for admin/forms.py looks somewhat like this:

```
Entry = swapper.load_model("zinnia", "Entry")

class EntryAdminForm(forms.ModelForm):
    """
    Form for Entry's Admin.
    """
   ...
   ...
   ...
    def __init__(self, *args, **kwargs):
        super(EntryAdminForm, self).__init__(*args, **kwargs)

        Entry = swapper.load_model("zinnia", "Entry")

        self.fields['categories'].widget = RelatedFieldWidgetWrapper(
            self.fields['categories'].widget,
            Entry.categories.field.remote_field,
            self.admin_site)

    class Meta:
        """
        EntryAdminForm's Meta.
        """
        model = Entry
        fields = forms.ALL_FIELDS
        ...
```

The documentation states that  swapper.load_model works only when the django has loaded all the models so probably defining the model = Entry in the class Meta seems incorrect to me. 

In that case will I need to import the default Entry model in the admin/forms.py and in the __init__ method of EntryAdmin, reload the Entry model via swapper.load_model (as already done) ?

If so it would be great if we could have the documentation updated about this.

**Comment by sheppard** [comment]
This should theoretically work with a single top level call to `load_model()`, since the `admin` is not loaded until after Django had loaded all the models.  If it can't find the model then perhaps the setting didn't match up for some reason.
